### ISSUE TITLE
launcher_windows

### ISSUE THREAD

**Issue by Bitpes-stablecoin** [Drakkar-Software/OctoBot-Launcher#30]
No logro iniciar octobot.exe en windows 7, para la version 2.0.0 (versiones anteriores iniciaban correctamente)
 Luego de iniciar launcher_app_windows.exe ,desde el navegador instalo y actualizo octobot y tentaculos,al dar clic en inicio de octobot,se recarga nuevamente la misma pantalla y el icono azul de iniciar octobot no funciona.
Al intentar desde el archivo octobot.exe, abre y cierra el cmd sin lograr iniciar

Cannot open self C:\Users\usuario\Downloads\octobot\OctoBot.exe or archive C:\Users\usuario\Downloads\octobot\OctoBot.pkg

¿que podría estar realizando mal y como  solucionarlo?

![Captura2](https://user-images.githubusercontent.com/25169084/55565325-02b34480-56d0-11e9-97b6-b0781a6526cb.png)

**Comment by GuillaumeDSM** [comment]
Hello javier,

Can you open a command line in the folder of your octobot.exe and type octobot.exe and tell us what the error is ?
This way the terminal won't instantly close and we will be able to figure out what is going wrong.

Thanks for using OctoBot !

**Comment by javiertuerca** [comment]
C:\Users\usuario\Downloads\octobot>octobot.exe
[4868] Cannot open self C:\Users\usuario\Downloads\octobot\OctoBot.exe or archive C:\Users\usuario\Downloads\octobot\OctoBot.pkg

C:\Users\usuario\Downloads\octobot>

**Comment by javiertuerca** [comment]
C:\Users\usuario\Downloads\octobot>octobot.exe
[4868] Cannot open self C:\Users\usuario\Downloads\octobot\OctoBot.exe or archive C:\Users\usuario\Downloads\octobot\OctoBot.pkg

C:\Users\usuario\Downloads\octobot>

**Comment by javiertuerca** [comment]
Un dato adicional,los valores sha1 podrian estar invertidos en la publicación,los datos que obtengo desde Windows son ;

            Binario                                                             SHA1
 launcher_app_windows.exe    513F906BF4C30919D7CF421D0A7633D86BCC74E1

 launcher_app_osx                   4C5F885B51AF949948CD55B9B3D2E22B5834B788

**Comment by GuillaumeDSM** [comment]
> Un dato adicional,los valores sha1 podrian estar invertidos en la publicación,los datos que obtengo desde Windows son ;
> 
> ```
>         Binario                                                             SHA1
> ```
> launcher_app_windows.exe 513F906BF4C30919D7CF421D0A7633D86BCC74E1
> 
> launcher_app_osx 4C5F885B51AF949948CD55B9B3D2E22B5834B788

Right ! I fixed this, thanks :)

**Comment by GuillaumeDSM** [comment]
> C:\Users\usuario\Downloads\octobot>octobot.exe
> [4868] Cannot open self C:\Users\usuario\Downloads\octobot\OctoBot.exe or archive C:\Users\usuario\Downloads\octobot\OctoBot.pkg
> 
> C:\Users\usuario\Downloads\octobot>

What type of OS are you using ? W10 x64 ?

**Comment by javiertuerca** [comment]
W 7 x64

**Comment by javiertuerca** [comment]
AL ejecutar por primera vez launcher_app_windows.exe y clic en instalar octobot,genera este error:

ERROR:root:Failed to download latest release data : ("Connection broken: ConnectionResetError(10054, 'Se ha forzado la interrupción de una c
onexión existente por el host remoto', None, 10054, None)", ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión exist
ente por el host remoto', None, 10054, None))
Traceback (most recent call last):
  File "site-packages\urllib3\response.py", line 360, in _error_catcher
  File "site-packages\urllib3\response.py", line 442, in read
  File "http\client.py", line 447, in read
  File "http\client.py", line 491, in readinto
  File "socket.py", line 589, in readinto
  File "ssl.py", line 1052, in recv_into
  File "ssl.py", line 911, in read
ConnectionResetError: [WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\models.py", line 750, in generate
  File "site-packages\urllib3\response.py", line 494, in stream
  File "site-packages\urllib3\response.py", line 459, in read
  File "contextlib.py", line 130, in __exit__
  File "site-packages\urllib3\response.py", line 378, in _error_catcher
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente
por el host remoto', None, 10054, None)", ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host r
emoto', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\usuario\Downloads\Octobot\launcher\tools\github.py", line 121, in update_binary
    return self.download_binary(latest_release_data)
  File "C:\Users\usuario\Downloads\Octobot\launcher\tools\github.py", line 93, in download_binary
    for chunk in r.iter_content(1024):
  File "site-packages\requests\models.py", line 753, in generate
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión ex
istente por el host remoto', None, 10054, None)", ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por e
l host remoto', None, 10054, None))
ERROR:root:No OctoBot found to update tentacles.
INFO:werkzeug:192.168.56.1 - - [04/Apr/2019 22:30:34] "GET /install HTTP/1.1" 200 -
[2604] Cannot open self C:\Users\usuario\Downloads\Octobot\OctoBot.exe or archive C:\Users\usuario\Downloads\Octobot\OctoBot.pkg
INFO:werkzeug:192.168.56.1 - - [04/Apr/2019 22:30:36] "GET /bot HTTP/1.1" 200 -

**Comment by GuillaumeDSM** [comment]
Ok, it looks like the launcher is not finding OctoBot.exe for some reason. Can you try downloading this version ? https://github.com/Drakkar-Software/OctoBot-Binary/releases which is the one that the launcher tries to download. 
The rename it OctoBot.exe and the launcher should find it from there

**Comment by javiertuerca** [comment]
si ,las versiones anteriores funcionan correctamente el inconveniente surgió en 2.0.0

**Comment by javiertuerca** [comment]
¿Podría ser esta configuración de registro W 7 que cause el inconveniente?

HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Rpc\RestrictRemoteClients REG_DWORD 1

 HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Rpc\EnableAuthEpResolutio REG_DWORD 1

**Comment by GuillaumeDSM** [comment]
That might be the reason yes. The thing is that we don't have any W7 to test it yet.
OctoBot launcher is a utility software, it's not required to use OctoBot, is OctoBot.exe working on your setup ?

**Comment by javiertuerca** [comment]
Gracias por tus respuesta ,no la version 2.0.0 para W 7 no esta funcionado ,instalare W 10 para seguir realizar test de octobot, Buenas tardes
