### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Sascha321** [Drakkar-Software/OctoBot-Launcher#53]
Hello I have downloaded the program "https://github.com/Drakkar-Software/OctoBot-Launcher/releases/download/2.0.4/launcher_app_linux" onto my Linux Ubuntu 20.04, but when I double-click nothing happens like can I install the program?

Gruss Sascha

**Comment by GuillaumeDSM** [comment]
Hi @Sascha321,
What happens when you start it from a terminal ?

**Comment by Herklos** [comment]
Hi @Sascha321, can you type `chmod +x launcher_app_linux` before retrying ?

**Comment by Sascha321** [comment]
Hello, I had to check for the "launcher_app_linux" that it is the program type program, now it works. Thank you.

Is there OctoBot also in German?

**Comment by Herklos** [comment]
Hi @Sascha321, we are working on internationalization but OctoBot is only in English for now. German was also ask in https://github.com/Drakkar-Software/OctoBot/issues/1293. We'll update this issue when it's available.
